# Generated by Django 4.2 on 2025-11-26 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('TRANSITO', 'En tránsito'), ('ALISTAMIENTO', 'En alistamiento'), ('POR_VERIFICAR', 'Por verificar'), ('VERIFICADO', 'Verificado'), ('EMPACADO', 'Empacado'), ('DESPACHADO', 'Despachado'), ('ENTREGADO', 'Entregado'), ('DEVUELTO', 'Devuelto')], max_length=20)),
                ('warehouse', models.CharField(max_length=50)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
